---
title: "Creating a Mayo-Themed HTML file"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: false
vignette: >
  %\VignetteIndexEntry{Creating a Mayo-Themed HTML file}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{css echo = FALSE}
.shadow {
  box-shadow: 0 .5rem 1rem rgba(0,0,0,.15) !important;
}
```


# Basic Usage

The theme can be used by including it in the document YAML, as shown below.

```yaml
---
title: "Mayo-Themed Rmarkdown"
author: First Last
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: mayodown::mayohtml
---
```

# Sample output

```{r echo=FALSE, include=FALSE}
rmarkdown::render("../inst/examples/html_example.Rmd", output_dir = ".")
```

<div class="embed-responsive embed-responsive-16by9 shadow">
<iframe  class="embed-responsive-item" align = "center" width = "100%" height = "600px" allow="fullscreen" src="html_example.html#zoom=133"/>
</div>

# Additional Arguments

`mayodown::mayohtml` uses the same core rendering engine as `rmarkdown::html_document` and can be passed the same parameters.  Some parameters have different default values set, however.

```yaml
---
title: "Mayo-Themed Rmarkdown"
author: First Last
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  mayodown::mayohtml:
    toc: true
    toc_float: true
    toc_depth: 2
---
```
